spring.application.name=linkforge

spring.datasource.url=jdbc:mysql://localhost:3306/linkforgedb
spring.datasource.username=root
spring.datasource.password=Amin23042007_

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=WfF1mJxj9cS6W6bY6qX5mT1r8gQx2d7b3hJ0kL9pQnM=
jwt.expiration=172800000
